/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jane' at '16-1-10 上午9:28' with Gradle 2.9
 *
 * @author jane, @date 16-1-10 上午9:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
